### PR TITLE
Improve context navigation

### PR DESCRIPTION
**Pull request by sayanarijit**
Add several navigation options:

- up/down or j/k - to navigate contexts
- tab/back-tab or ctrl-n/ctrl-p - to navigate initialized contexts
- q to quit contexts

Also, some code refactor.

### CODE REVIEW

**Comment by sayanarijit** [comment]
csw

**Comment by sayanarijit** [comment]
Wait, I can add `q` to close contexts.

**Comment by sayanarijit** [comment]
csw-quit

**Comment by sayanarijit** [comment]
Done.

**Comment by igorepst** [comment]
@sayanarijit Thank you!

**Pull request merged**
